(cl:in-package #:viewpoints)

(defun get-tonint (cpitch octave keysig mode)
  (- cpitch
     (+ (* octave *octave*)
	(get-referent keysig mode))))

(define-abstract-viewpoint (abs-tonint (cpitch) (:keysig :mode) () abs-tonint-training)
    ((events md:melodic-sequence) element) 
  :function (lambda (keysig mode)
	      (get-tonint (cpitch events) (octave (list (car events)))
			  keysig mode)))

(define-abstract-viewpoint (abs-sdeg-west (cpitch) (:keysig :mode) () abs-sdeg-west-training)
    ((events md:melodic-sequence) element) 
  :function (lambda (keysig mode)
	      (let* ((pitch (cpitch events))
		     (interval (get-tonint pitch (octave (list (car events)))
					   keysig mode))
		     (scale-intervals (case mode
					(0 viewpoints::*major-intervals*)
					(9 viewpoints::*minor-intervals*)))
		     (degree (degree interval scale-intervals)))
		(if (null degree)
		    pitch
		    (+ degree
		       (* (- (utils:quotient interval *octave*)
			     (if (< interval 0) 1 0))
			  7))))))

(define-abstract-viewpoint (abs-sdeg-west-2 (cpitch) (:keysig :mode) () abs-sdeg-west-2-training)
    ((events md:melodic-sequence) element) 
  :function (lambda (keysig mode)
	      (let* ((pitch (cpitch events))
		     (interval (get-tonint pitch 0 keysig mode)))
		(mod interval *octave*)))
  :function* (lambda (keysig mode)
		 (remove-if #'(lambda (e) (not (eq (mod (get-tonint e 0 keysig mode) *octave*)
						   element)))
			    (viewpoint-alphabet (get-viewpoint 'cpitch))))
  :alphabet (lambda (&rest args)
	      (declare (ignore args))
	      (utils:generate-integers 0 (1- *octave*))))


(define-viewpoint (sdeg-west-3 derived (cpitch))
    ((events md:melodic-sequence) element) 
  :function (let* ((interval (tonint events))
		   (scale-intervals (case (mode events)
				      (0 viewpoints::*major-intervals*)
				      (9 viewpoints::*minor-intervals*)))
		   (degree (degree interval scale-intervals)))
	      (if (null degree)
		  (- (mod interval *octave*))
		  degree)))

(define-abstract-viewpoint (abs-sdeg-west-3 (cpitch) (:keysig :mode) () abs-sdeg-west-3-training)
    ((events md:melodic-sequence) element) 
  :function (lambda (keysig mode)
	      (let* ((pitch (cpitch events))
		     (interval (get-tonint pitch (octave (list (car events)))
					   keysig mode))
		     (scale-intervals (case mode
					(0 viewpoints::*major-intervals*)
					(9 viewpoints::*minor-intervals*)))
		     (degree (degree interval scale-intervals)))
		(if (null degree)
		    (- (mod interval *octave*))
		    degree))))

