(cl:in-package #:latent-variables)

(defgeneric interpretation-parameters (variable))
(defgeneric category-parameters (variable))
(defgeneric latent-variable-attribute (variable))
(defgeneric latent-variable-name (variable))
(defgeneric latent-state-parameters (variable))
(defgeneric get-category-parameter (category parameter variable))
(defgeneric get-interpretation-parameter (interpretation parameter variable))
(defgeneric get-latent-state-parameter (interpretation parameter variable))
(defgeneric get-category (latent-state variable))
(defgeneric get-interpretation (latent-state variable))
(defgeneric get-link-category (linked-variable category link))
(defgeneric get-event-category (event variable))
(defgeneric get-latent-states (category variable))
(defgeneric get-latent-variable-state (variable))
(defgeneric get-prior-distribution (training-data categories variable))
(defgeneric set-link-categories (variable))
(defgeneric get-link-categories (variable link))
(defgeneric create-category (variable &rest parameters))
(defgeneric create-latent-state (variable category &rest parameters))
(defgeneric initialise-prior-distribution (training-data variable))
(defgeneric get-link-training-sets (training-data linked))
(defgeneric combine-prior-distributions (linked))
(defgeneric combine-link-parameters (linked parameter-sets &key parameter-name-fn))
(defgeneric combine-link-categories (linked categories))
(defgeneric combine-link-latent-states (linked latent-states))
