(cl:in-package #:latent-variables)

(defgeneric interpretation-attributes (variable))
(defgeneric category-attributes (variable))
(defgeneric latent-variable-attribute (variable))
(defgeneric latent-variable-name (variable))
(defgeneric latent-state-attributes (variable))
(defgeneric get-category-attribute (category attribute variable))
(defgeneric get-interpretation-attribute (interpretation attribute variable))
(defgeneric get-latent-state-attribute (interpretation attribute variable))
(defgeneric get-category (latent-state variable))
(defgeneric get-interpretation (latent-state variable))
(defgeneric get-link-category (linked-variable category link))
(defgeneric get-event-category (event variable))
(defgeneric get-latent-states (category variable))
(defgeneric get-latent-variable-state (variable))
(defgeneric get-prior-distribution (training-data categories variable))
(defgeneric set-link-categories (variable))
(defgeneric get-link-categories (variable link))
(defgeneric create-category (variable &rest attributes))
(defgeneric create-latent-state (variable category &rest attributes))
(defgeneric initialise-prior-distribution (training-data variable))
(defgeneric get-link-training-sets (training-data linked))
(defgeneric combine-prior-distributions (linked))
(defgeneric combine-link-attributes (linked attribute-sets &key attribute-name-fn))
(defgeneric combine-link-categories (linked categories))
(defgeneric combine-link-latent-states (linked latent-states))
